AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 10
    Runtime: python3.10

Resources:
  TaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/tasks/
      Handler: app.lambda_handler
      Role: arn:aws:iam::${AWS::AccountId}:role/task-lambda-role-${Environment}
      Events:
        TaskAPI:
          Type: Api
          Properties:
            Path: /tasks
            Method: ANY

  AttachmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/attachments/
      Handler: app.lambda_handler
      Role: arn:aws:iam::${AWS::AccountId}:role/attachments-lambda-role-${Environment}
