AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 10
    Runtime: python3.10

Resources:
  TaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/task/
      Handler: app.lambda_handler
      Role:  !Sub arn:aws:iam::413600747077:role/task-lambda-role-dev
      Events:
        TaskAPI:
          Type: Api
          Properties:
            Path: /tasks
            Method: ANY

  AttachmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/attachments/
      Handler: app.lambda_handler
      Role:  !Sub arn:aws:iam::413600747077:role/attachments-lambda-role-dev
