AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Aplicacion Lambda con API Gateway

Resources:
  TaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TaskFunction
      Handler: task.app.lambda_handler
      Runtime: python3.10
      Role: arn:aws:iam::413600747077:role/GitHubActionsRole
      Policies: GitHubActionsRole-ToDoCreate-Role
      CodeUri: src/lambdas/task/
      Description: Función Lambda de ejemplo
      MemorySize: 128
      Timeout: 5
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  HelloWorldApi:
    Description: "URL de invocación de la API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
